version: "3"

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:7001'
        gitlab_rails['gitlab_shell_ssh_port'] = 7002
        registry_external_url 'http://localhost:4567'
#        registry_nginx['ssl_certificate'] = "/certs/gitlabswarm:4567.crt"
#        registry_nginx['ssl_certificate_key'] = "/certs/gitlabswarm:4567.key"
    ports:
      - '7001:7001'
      - '7002:22'
      - '4567:4567'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
      - '/etc/hosts:/etc/hosts'
      #- '/home/jun/projects/ciRobotPP/gitlab:/home/git/data'
      #- '/home/u16/projects/ciRobotics/certs:/certs'
    networks:
      - gitlab


  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      - '/srv/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/etc/hosts:/etc/hosts'
    networks:
      - gitlab


  gitlab-runner-register:
    image: 'gitlab/gitlab-runner:latest'
    restart: 'no'
    volumes:
      - '/srv/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/etc/hosts:/etc/hosts'
    command:
    - register
    - --non-interactive
    - --locked=false
    - --name=Docker Runner
    - --executor=docker
    - --docker-image=docker:17.09.0-ce-dind
    - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    - --docker-network-mode=services_gitlab
    - --docker-pull-policy=if-not-present
    environment:
    - CI_SERVER_URL=http://gitlab:7001
    - REGISTRATION_TOKEN=pf91N9aRFyrTZhjRdyEB
    - CLONE_URL=http://gitlab:7001
#    - docker-network-mode=services_gitlab
    networks:
      - gitlab

networks:
  gitlab:

